SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS NOTICE_INFO;
DROP TABLE IF EXISTS OFF_USE_INFO;
DROP TABLE IF EXISTS OFF_INFO;
DROP TABLE IF EXISTS SALARY_INFO;
DROP TABLE IF EXISTS USER_CERTI;
DROP TABLE IF EXISTS USER_INFO;
DROP TABLE IF EXISTS DEPART_INFO;
DROP TABLE IF EXISTS GRADE_INFO;




/* Create Tables */

CREATE TABLE DEPART_INFO
(
	DI_NUM int NOT NULL AUTO_INCREMENT,
	DI_NAME varchar(30) NOT NULL,
	DI_DESC varchar(4000),
	PRIMARY KEY (DI_NUM),
	UNIQUE (DI_NAME)
);


CREATE TABLE GRADE_INFO
(
	GI_NUM int NOT NULL AUTO_INCREMENT,
	GI_NAME varchar(30) NOT NULL,
	GI_DESC varchar(4000),
	PRIMARY KEY (GI_NUM),
	UNIQUE (GI_NAME)
);


CREATE TABLE NOTICE_INFO
(
	-- 공지사항번호
	NI_NUM int NOT NULL AUTO_INCREMENT COMMENT '공지사항번호',
	-- 공지사항제목
	NI_TITLE varchar(200) NOT NULL COMMENT '공지사항제목',
	-- 공지사항내용
	NI_CONTENT text NOT NULL COMMENT '공지사항내용',
	-- 공지사항파일경로
	NI_FILE_PATH varchar(300) COMMENT '공지사항파일경로',
	-- 공지사항조회수
	NI_CNT int DEFAULT 0 NOT NULL COMMENT '공지사항조회수',
	-- 생성일자
	CREDAT char(8) DEFAULT 'DATE_FORMAT(NOW(),''%Y%m%d'')' NOT NULL COMMENT '생성일자',
	-- 생성시간
	CRETIM char(6) DEFAULT 'DATE_FORMAT(NOW(),''%h%i%s'')' NOT NULL COMMENT '생성시간',
	-- 활성여부
	ACTIVE char(1) DEFAULT '1' NOT NULL COMMENT '활성여부',
	UI_NUM int NOT NULL,
	PRIMARY KEY (NI_NUM)
);


CREATE TABLE OFF_INFO
(
	OI_NUM int NOT NULL AUTO_INCREMENT,
	OI_YEAR char(4) NOT NULL,
	OI_DAY tinyint DEFAULT 15,
	UI_NUM int NOT NULL,
	PRIMARY KEY (OI_NUM),
	UNIQUE (OI_DAY)
);


CREATE TABLE OFF_USE_INFO
(
	OUI_NUM int NOT NULL AUTO_INCREMENT,
	OUI_DAY char(4) NOT NULL,
	OUI_TYPE char(1) DEFAULT '1' NOT NULL,
	OUI_START char(8) NOT NULL,
	OUI_END char(8) NOT NULL,
	OUI_STATUS char(1) DEFAULT '0' NOT NULL,
	OI_NUM int NOT NULL,
	PRIMARY KEY (OUI_NUM)
);


CREATE TABLE SALARY_INFO
(
	UI_NUM int NOT NULL,
	SI_NUM int NOT NULL,
	BASE_PAY int NOT NULL,
	EXTENSION_ALLOWANCE int,
	MEAL_ALLOWANCE int NOT NULL,
	OVERTIME_ALLOWANCE int,
	CARMAINTENANCE int NOT NULL,
	EDU_EXPENSE int NOT NULL,
	DURT_ALLOWANCE int NOT NULL,
	SPECIAL_ALLOWANCE int,
	RETIREMENT_PAY int,
	PRIMARY KEY (SI_NUM)
);


CREATE TABLE USER_CERTI
(
	-- 재직증명서 번호
	UC_NUM int NOT NULL AUTO_INCREMENT COMMENT '재직증명서 번호',
	PERIOD_START char(8),
	PERIOD_END char(8),
	-- 재직증명서용도
	UC_TYPE char(1) DEFAULT '1' NOT NULL COMMENT '재직증명서용도',
	UC_ACTIVE char(1) DEFAULT '2' NOT NULL,
	CREDAT char(8) NOT NULL,
	CRETIM char(6) NOT NULL,
	UI_NUM int NOT NULL,
	PRIMARY KEY (UC_NUM)
);


CREATE TABLE USER_INFO
(
	UI_NUM int NOT NULL AUTO_INCREMENT,
	UI_ID varchar(30) NOT NULL,
	UI_NAME varchar(30) NOT NULL,
	UI_PWD varchar(30) NOT NULL,
	UI_BIRTH char(8) NOT NULL,
	UI_TRANS char(1) DEFAULT '1' NOT NULL,
	CREDAT char(8),
	CRETIM char(6),
	OUTDAT char(8),
	ACTIVE char(1) DEFAULT '1',
	UI_LVL char(1) DEFAULT '2' NOT NULL,
	UI_EMAIL varchar(200) NOT NULL,
	-- 유저정보담당업무
	UI_DUTIES varchar(10) DEFAULT '사무' NOT NULL COMMENT '유저정보담당업무',
	GI_NUM int NOT NULL,
	DI_NUM int NOT NULL,
	PRIMARY KEY (UI_NUM),
	UNIQUE (UI_ID)
);



/* Create Foreign Keys */

ALTER TABLE USER_INFO
	ADD FOREIGN KEY (DI_NUM)
	REFERENCES DEPART_INFO (DI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_INFO
	ADD FOREIGN KEY (GI_NUM)
	REFERENCES GRADE_INFO (GI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE OFF_USE_INFO
	ADD FOREIGN KEY (OI_NUM)
	REFERENCES OFF_INFO (OI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE NOTICE_INFO
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE OFF_INFO
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SALARY_INFO
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_CERTI
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



